In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('new-site.csv')
data.head()

  site\tdwell-time
0             0\t2
1            1\t48
2            0\t15
3            1\t16
4            0\t38

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   site	dwell-time  300 non-null    object
dtypes: object(1)
memory usage: 2.5+ KB

In [12]:
df=data['site\tdwell-time'].str.split('\t', expand=True)

In [13]:
df.head()

   0   1
0  0   2
1  1  48
2  0  15
3  1  16
4  0  38

In [14]:
df.columns=['site', 'time']

In [36]:
df['time']=df['time'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   site    300 non-null    object
 1   time    300 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.8+ KB

In [16]:
df['time'].sum()

'24815163816957138233146336575475551382630322136976162231901073014525233327972179867823132446834851122987264453118014029519242219218110404043043129722713818516145948158793573138022893428519267251492329219576763418436681315012813112313610282135717011566471123748144672691614011463536912221528312246112441857552596310750540345111364891471542949134124191831963012127725507475661338741091323741664733358223624161203003235315540462175704914014018167526244482611071255116485127171471932682923117267053121373113172200174135133451171031612510566277156285648607030952268781952760122834661148111491861101751107331067214815336643238100187117015554702838819731002523922714489138'

In [24]:
df.groupby(['site']).agg(['mean'])

           time
           mean
site
0     90.849462
1     88.000000

In [25]:
from scipy import stats
import statsmodels.api as sm
from statsmodels import stats as sms

In [26]:
# функция для принятия решения о нормальности
def decision_normality(p):
    print('p-value = {:.3f}'.format(p))
    if p <= alpha:
        print('p-значение меньше, чем заданный уровень значимости {:.2f}. Распределение отлично от нормального'.format(alpha))
    else:
        print('p-значение больше, чем заданный уровень значимости {:.2f}. Распределение является нормальным'.format(alpha))


# функция для принятия решения об отклонении нулевой гипотезы
def decision_hypothesis(p):
    print('p-value = {:.3f}'.format(p))
    if p <= alpha:
        print('p-значение меньше, чем заданный уровень значимости {:.2f}. Отвергаем нулевую гипотезу в пользу альтернативной.'.format(alpha))
    else:
        print('p-значение больше, чем заданный уровень значимости {:.2f}. У нас нет оснований отвергнуть нулевую гипотезу.'.format(alpha))

In [37]:
A = df.loc[df['site']=='0', 'time']
B = df.loc[df['site']=='1', 'time']

In [40]:
result = stats.shapiro(A)
alpha=0.05
decision_normality(result[1])

p-value = 0.000
p-значение меньше, чем заданный уровень значимости 0.05. Распределение отлично от нормального

In [41]:
result = stats.shapiro(B)
alpha=0.05
decision_normality(result[1])

p-value = 0.000
p-значение меньше, чем заданный уровень значимости 0.05. Распределение отлично от нормального

In [43]:
_, p = stats.mannwhitneyu(A, B, alternative='two-sided')
decision_hypothesis(p)

p-value = 0.896
p-значение больше, чем заданный уровень значимости 0.05. У нас нет оснований отвергнуть нулевую гипотезу.